sudo: false
language: Python
services:
  - docker

git:
    depth: 100500

env:
    matrix:
      - OS=el DIST=8

script:
 - ls -al .
 - pwd
 - wget https://tkn.me/tmp/python-gevent-1.1.2-2.el8.src.rpm
 - wget https://tkn.me/tmp/python-gevent-debugsource-1.1.2-2.el8.x86_64.rpm
 - wget https://tkn.me/tmp/python2-gevent-1.1.2-2.el8.x86_64.rpm
 - wget https://tkn.me/tmp/python2-gevent-debuginfo-1.1.2-2.el8.x86_64.rpm
 - ls -al *el8*.rpm

deploy:
  # Deploy packages to PackageCloud
  provider: packagecloud
  username: ${PACKAGECLOUD_USER}
  repository: ${PACKAGECLOUD_REPO}
  token: ${PACKAGECLOUD_TOKEN}
  dist: ${OS}/${DIST}
  package_glob: build/*.{rpm}
  skip_cleanup: true
  on:
    all_branches: true
    condition: -n "${OS}" && -n "${DIST}" && -z "${ARCH}" && -n "${PACKAGECLOUD_TOKEN}"

notifications:
  email: true
